### PR TITLE
Rolling back markdown-translatable

### PR DESCRIPTION
**Pull request by ancientTexts-net**
should be good to merge now thank you

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/528)

### CODE REVIEW

**Comment by ancientTexts-net** [comment]
Should be good to review now!  Thank you!

**Comment by ancientTexts-net** [comment]
Testable @ https://5fbd0a1c4527ee012211d203--tc-create-app.netlify.app/

**Review by mandolyte — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/528)* status: all files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net)

___
*[debug.log, line 1 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/528#-MMuvlEe1sKBmSxCoqKE:-MMuvlEe1sKBmSxCoqKF:b-ze0b73) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/79e4f1f32128b7fd6723973920751f05e4551d04/debug.log#L1)):*
> ```
> [1117/152556.565:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
> ```

Delete this file?

**Review by mandolyte — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/528)* status: all files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net)

**Review by mandolyte — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/528)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ancientTexts-net)

**Pull request merged**
