### PR TITLE
Auto save merge into develop test 1219

### PR DESCRIPTION
**Pull request by ancientTexts-net**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/1113)

### CODE REVIEW

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose

**Comment by ancientTexts-net** [comment]
THANK YOU  :DDD

**Comment by ancientTexts-net** [comment]
FYI these TEST NOTES assume # 921 is also completed

**Review by jincypjose — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 8 of 14 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/1113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Joel-C-Johnson)

**Review by Joel-C-Johnson — APPROVED** [review]

**Pull request merged**
