### PR TITLE
autosave prompt

### PR DESCRIPTION
**Pull request by ancientTexts-net**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/1116)

### CODE REVIEW

**Comment by ancientTexts-net** [comment]
@jincypjose @Joel-C-Johnson 

Thank you so much for your help

**Comment by ancientTexts-net** [comment]
@elsylambert 

I can put updated test notes in issue # 921

https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/921

**Comment by mandolyte** [comment]
My test notes are [here](https://github.com/mandolyte/uw-journal/blob/main/apps/tc-create-app/Testing%20Autosave.md)

I had two comments:

On scenario 1:
Question: at the end of the scenario, the save button is not active, even tho I have unsaved content. Which is to say, on QA DCS, my branch exists with the old version of Jude, not my changed version. If I really want to save the content, I'll have to make another change. then the button will become active, enabling me to save. Is this OK?


On scenario 3: I used a different computer to make the change instead of simulating by editing directly in DCS.

**It did not prompt to discard or keep. It simply went to the latest file in my branch which I had changed on the other computer.**

**Review by jincypjose — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/1116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ancientTexts-net)

**Comment by jincypjose** [comment]
code looks good to.Have reviewed by me and @ancientTexts-net

**Pull request merged**
