### PR TITLE
"save retry" error handling

### PR DESCRIPTION
**Pull request by ancientTexts-net**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/419)

### CODE REVIEW

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/419)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @ancientTexts-net, @mandolyte, and @RoyalSix 
___
*[src/components/translatable/Translatable.js, line 55 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSgflQ7GS9hFYmUvYz:-MJSgflQ7GS9hFYmUvZ-:b9gb1yv) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L55)):*
> ```JavaScript
>       }
>     }
>   }, [authentication, targetFile, targetFileActions, targetFileActions.save]);
> ```

Eslint told me there are missing dependencies in this array `[authentication, isAuthenticationModalVisible, savingTargetFileContent, targetFileActions, targetFileActions.save]` and one extra 
___
*[src/components/translatable/Translatable.js, line 71 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSgpPoAb_wNW2TG7HD:-MJSgpPoAb_wNW2TG7HE:b-ew43w8) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L71)):*
> ```JavaScript
>           });
>     }
>   }, [doSaveRetry]);
> ```

Eslint told me there are missing dependencies in this array `[doSaveRetry, savingTargetFileContent, targetFileActions]`
___
*[src/components/translatable/Translatable.js, line 97 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSg7MR5-pcEDrHyMnD:-MJSg7MR5-pcEDrHyMnE:bystjp1) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L97)):*
> ```JavaScript
>     );
>   }, [config, isAuthenticationModalVisible, classes.modal,
>     , authenticationActions, authenticationActions.onLoginFormSubmitLogin
> ```

Eslint told me there is unnecessary dependencies in this array
All you need is the following `[config, isAuthenticationModalVisible, classes.modal, authenticationActions]`
___
*[src/components/translatable/Translatable.js, line 120 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSf4Jg1NgVE8hOx_2Y:-MJSf4Jg1NgVE8hOx_2Z:b-rmzzwn) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L120)):*
> ```JavaScript
>           await targetFileActions.save(content);
>         } catch (error) {
>           openAuthenticationModal();
> ```

Is there a specific error/error code we are getting back that we know needs authentication?

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/419)* status: all files reviewed, 4 unresolved discussions (waiting on @ancientTexts-net and @mandolyte)

**Comment by ancientTexts-net** [comment]
___
*[src/components/translatable/Translatable.js, line 71 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSgpPoAb_wNW2TG7HD:-MJXj-mh63_PfxjnkLh9:b-896fix) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L71)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Eslint told me there are missing dependencies in this array `[doSaveRetry, savingTargetFileContent, targetFileActions]`
</blockquote></details>

Done.

**Comment by ancientTexts-net** [comment]
___
*[src/components/translatable/Translatable.js, line 55 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSgflQ7GS9hFYmUvYz:-MJXj19E0LUlSOTXEj6p:b-896fix) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L55)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Eslint told me there are missing dependencies in this array `[authentication, isAuthenticationModalVisible, savingTargetFileContent, targetFileActions, targetFileActions.save]` and one extra 
</blockquote></details>

Done.

**Comment by ancientTexts-net** [comment]
___
*[src/components/translatable/Translatable.js, line 55 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSgflQ7GS9hFYmUvYz:-MJXj4BvDf-yR4XyxMgG:b5kh5d5) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L55)):*
<details><summary><i>Previously, ancientTexts-net (Zach Pennington) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

must exclude isAuthenticationModalVisible
since we set isAuthenticationModalVisible via closeAuthenticationModal

**Comment by ancientTexts-net** [comment]
___
*[src/components/translatable/Translatable.js, line 97 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSg7MR5-pcEDrHyMnD:-MJXjzZq0pNKUtrx_svW:b-896fix) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L97)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Eslint told me there is unnecessary dependencies in this array
All you need is the following `[config, isAuthenticationModalVisible, classes.modal, authenticationActions]`
</blockquote></details>

Done.

**Comment by ancientTexts-net** [comment]
___
*[src/components/translatable/Translatable.js, line 97 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSg7MR5-pcEDrHyMnD:-MJXk-W65tmiYplm6DjZ:b750ifa) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L97)):*
<details><summary><i>Previously, ancientTexts-net (Zach Pennington) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you Jay

**Comment by ancientTexts-net** [comment]
___
*[src/components/translatable/Translatable.js, line 120 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/419#-MJSf4Jg1NgVE8hOx_2Y:-MJY9YcbEH3p8AgMv0RS:b-896fix) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/55092f3a519bf1a5f16094f2300a32bee0d576d3/src/components/translatable/Translatable.js#L120)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Is there a specific error/error code we are getting back that we know needs authentication?
</blockquote></details>

Done.

**Review by RoyalSix — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/419)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mandolyte)

**Pull request merged**
