### PR TITLE
Added merging and updating functionality for master

### PR DESCRIPTION
**Pull request by jincypjose**
Added merging and updating functionality for master

### CODE REVIEW

**Comment by elsylambert** [comment]
@jincypjose Can you please link it to an issue?

**Comment by abelpz** [comment]
@els

> @jincypjose Can you please link it to an issue?

I think this is a duplicated PR we started working on this branch but then created a different one for this. This feature is already in production.

**Comment by elsylambert** [comment]
Is it okay to close this one? @abelpz

**Comment by abelpz** [comment]
Yes @elsylambert I'll go ahead and to that.

**Pull request closed without merging**
