### PR TITLE
changes for GRT 1.0.1-rc2

### PR DESCRIPTION
**Pull request by mandolyte**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/192)

### CODE REVIEW

**Comment by mandolyte** [comment]
Unable to connect it to tc-create-app issue #15. Does show in the dropdown.

**Comment by ancientTexts-net** [comment]
___
*[.env, line 2 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/192#-MBpZDeO1m9V3EP_WWSK:-MBpZDeO1m9V3EP_WWSL:bt1bfdv) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/f69f9bf760ca8ef8dad8a000c87c741c15cb76fa/.env#L2)):*
> ```
> REACT_APP_DOOR43_SERVER_URL
> ```
is this OK in PROD?

**Comment by ancientTexts-net** [comment]
___
*[.env, line 2 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/192#-MBpZDeO1m9V3EP_WWSK:-MBpZJUGAV59RiX7jkoN:b5kkx4) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/f69f9bf760ca8ef8dad8a000c87c741c15cb76fa/.env#L2)):*
<details><summary><i>Previously, ancientTexts-net (Zach Pennington) wrote…</i></summary><blockquote>

> ```
> REACT_APP_DOOR43_SERVER_URL
> ```
is this OK in PROD?
</blockquote></details>

@mandolyte  ^^

**Comment by mandolyte** [comment]
No! I didn't think I checked that in. Does the GitHub Action set it based
on the target env?

QA may be right for QA purposes... But shouldn't be there for the master
branch.

**Comment by ancientTexts-net** [comment]
___
*[src/core/useStateReducer.js, line 89 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/192#-MBt3f-8AF8zEnHYmjC6:-MBt3f-8AF8zEnHYmjC7:b-9k1w80) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/f69f9bf760ca8ef8dad8a000c87c741c15cb76fa/src/core/useStateReducer.js#L89)):*
> ```JavaScript
>       if (JSON.stringify(value) !== JSON.stringify(state.authentication)) {
>         dispatch({ type: 'set_authentication', value });
>         /*
> ```

@mandolyte : if this block is commented, should it just be removed?  or additional comments on why it is left here in the meantime?

**Pull request merged**
