### PR TITLE
Early Fast Scrolling Fix

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/333)

### CODE REVIEW

**Comment by mandolyte** [comment]
@RoyalSix @ancientTexts-net I reviewed the changes. I don't understand why it works, but the changes themselves look OK.

Thus, I'll let someone else pull the trigger on the merge!

**Comment by ancientTexts-net** [comment]
thank you @mandolyte

**Comment by ancientTexts-net** [comment]
___
*[src/components/translatable/RowHeader.js, line 43 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/333#-MFA-X-V2UEweLnCEftk:-MFA-X-V2UEweLnCEftl:b-k9lvss) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/73d4727a74144f3ec40558760b13e88396ba0d20/src/components/translatable/RowHeader.js#L43)):*
> ```JavaScript
>   const component = useMemo(() => {
>     let _component = (
>       <Waypoint onEnter={onEnter}>
> ```

looks like the key is that the <Waypoint/> was removed?

**Comment by ancientTexts-net** [comment]
looks like the key is that the <Waypoint/> was removed?

**Comment by ancientTexts-net** [comment]
Waypoint wrapper

**Comment by ancientTexts-net** [comment]
looks like the key is that the Waypoint wrapper was removed?

**Comment by ancientTexts-net** [comment]
___
*[package.json, line 4 at r1](https://reviewable.io/reviews/unfoldingword/tc-create-app/333#-MFA0Z5C2rHCxDkcUYu6:-MFA0Z5C2rHCxDkcUYu7:b-b96e1z) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/a98f32f30ebf08316fd0932e51ba624ef399ee8b/package.json#L4)):*
> ```JSON
>   "name": "tc-create-app",
>   "homepage": "https://create.translationcore.com/",
>   "version": "1.0.3-rc.2",
> ```

Thanks.  My apologies for invalid `version`

**Pull request merged**
