### PR TITLE
Feature cn 953 add sn sq

### PR DESCRIPTION
**Pull request by mandolyte**
- this PR adds support for both Study Notes and Study Questions (en_sn, en_sq repositories).
- neither has any released content yet (and are quite imcomplete); thus can only be tested in an editor role (uW org and English language)
- Dependencies
   - uw-tsv-parser v1.0.1 (see package.json)
   - datatable-translatable that accepts above TSV parser. Not in NPM at this writing; must use branch `feature-cn-788-impl-tsv-parser`

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/1003)

### CODE REVIEW

**Comment by ancientTexts-net** [comment]
Tagging @Joel-C-Johnson @jincypjose 
to follow this issue please :) :)

**Comment by ancientTexts-net** [comment]
2021-08-30 12_38_02-Work-UnfoldingWord-2021 - VMware Workstation 16 Player (Non-commercial use only)


2021-08-30 12_41_23-Work-UnfoldingWord-2021 - VMware Workstation 16 Player (Non-commercial use only)


2021-08-30 12_39_40-Work-UnfoldingWord-2021 - VMware Workstation 16 Player (Non-commercial use only)

**Comment by mandolyte** [comment]
The above examples show that the new tsv parser is not being used. It is
passed by tc create to datatable-translatable as an optional parameter.

Needs the version that is currently in the tsv impl branch...

**Comment by mandolyte** [comment]
@ancientTexts-net looks like somehow that tN omits the scripture pane when there is an invalid reference. I think it may just be testing to see if the chapter & verse are numeric. I know one of the upcoming projects is work on verse ranges... it's going to get more complicated.

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose 

image

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose 

Video from the review

https://drive.google.com/file/d/1M1VU3zl-h9eLlJOFpV0GlZzJgvQQGhHi/view?usp=sharing

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose 
Are you seeing these review notes please?
Is this convenient?

**Comment by ancientTexts-net** [comment]
@jincypjose @Joel-C-Johnson 

NOT URGENT :D

But one thing we should test is: CONTENT VALIDATOR
for SN & SQ

image

**Comment by ancientTexts-net** [comment]
last week we received this error:

**Comment by ancientTexts-net** [comment]
the proposed changes were in the RCL:

https://github.com/unfoldingWord/uw-tsv-parser/commits/fix-JincyJoelZach-953-tcc-crash-parsercontent

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose @mandolyte

**Comment by ancientTexts-net** [comment]
@mandolyte 

Can you please help me with permissions on NPM here?
Is there something different about this new repo, that I can't publish?

Thank you

**Comment by mandolyte** [comment]
@ancientTexts-net @jincypjose @Joel-C-Johnson I have begun working on the content validation problem. After some analysis, here is my plan, which I'll start on tomorrow:
- refactor tN 9col TSV so that common code for CV can be re-used. Once it is working again, then...
- leverage the CV interfacing code in TN (7col), TWL, SN, SQ, and TQ

Sound OK?

**Comment by mandolyte** [comment]
@ancientTexts-net I have completed the refactor of the CV integration.
@elsylambert In addition, in the related branch, I have added:
- upgraded to latest cv pkg: v2.2.5
- added on-demand validation for TWL, SN, SQ, TN (7col version which isn't available yet).

Todo:
- Add CV for TQ
- Determine whether TQ should have quote selector (scripture references). They are not there now!

**Comment by mandolyte** [comment]
OK, @ancientTexts-net CV is now in TQ... I'll move this back to the review lane so you can review... thanks.

**Pull request merged**
