### PR TITLE
Feature cn 122 license info

### PR DESCRIPTION
**Pull request by mandolyte**
Since manifest info isn't available yet, in all contexts, the tooltip for the info icon does not try to show it. Instead:
image

This uses:
```
    "gitea-react-toolkit": "^1.0.0-beta.7",
    "scripture-resources-rcl": "^0.14.2",
```

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/135)

### CODE REVIEW

**Comment by mandolyte** [comment]
@elsylambert this is a preview for the remaining license info changes. Notes comments above.

**Comment by klappy** [comment]
___
*[package.json, line 36 at r2](https://reviewable.io/reviews/unfoldingword/tc-create-app/135#-M78CGrP6CZntaOQsso4:-M78CGrP6CZntaOQsso5:b9c6nyj) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/6e76d805622ff33caec142ecf03cfc7489fa8433/package.json#L36)):*
> ```JSON
>     "datatable-translatable": "^0.8.0",
>     "deep-freeze": "^0.0.1",
>     "gitea-react-toolkit": "^1.0.0-beta.7",
> ```

Somehow `gitea-react-toolkit` and `markdown-translateable` got downgraded in this PR. I would use what ever is currently in master branch.

**Comment by klappy** [comment]
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/unfoldingword/tc-create-app/135#-M78D1x5AFodlufmPCgq:-M78D1x5AFodlufmPCgr:b-nxbhg4) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/6e76d805622ff33caec142ecf03cfc7489fa8433/README.md#L21)):*
> ```Markdown
> - When `master` is updated, production will be deployed: https://tc-create-app.netlify.com
> 
> ## Using a feature branch in an RCL
> ```

Maybe we should move all of this to something else other than the README. This is what is presented first to all visitors to the RCL on Github, Netlify and NPM.

**Comment by klappy** [comment]
___
*[src/components/files-header/FilesHeader.js, line 9 at r2](https://reviewable.io/reviews/unfoldingword/tc-create-app/135#-M78DM8Y3GRNHu0DZKgk:-M78DM8Y3GRNHu0DZKgl:b-9z1zs0) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/6e76d805622ff33caec142ecf03cfc7489fa8433/src/components/files-header/FilesHeader.js#L9)):*
> ```JavaScript
> } from '@material-ui/core';
> import {
>   //Translate,
> ```

We could remove this since it is no longer used.

**Comment by klappy** [comment]
___
*[src/components/files-header/FilesHeader.js, line 71 at r3](https://reviewable.io/reviews/unfoldingword/tc-create-app/135#-M78ny4B7AU8YbNUVfHD:-M78ny4B7AU8YbNUVfHE:bub93n5) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/30b321dcada4105889be968ea7609f99fe4df785/src/components/files-header/FilesHeader.js#L71)):*
> ```JavaScript
>     const iconTooltip='OpenSourceText';
>     const deleteIconTooltip = 'CompareSource'
>     const licenseLink= sourceRepository.html_url+'/src/branch/master/LICENSE.md';
> ```

This should be different based on the branches of the source/target repository.
The left should be this one and the right one should be: `https://bg.door43.org/unfoldingWord/en_tn/src/branch/klappy-tc-create-1/LICENSE.md`

**Comment by mandolyte** [comment]
___
*[src/components/files-header/FilesHeader.js, line 71 at r3](https://reviewable.io/reviews/unfoldingword/tc-create-app/135#-M78ny4B7AU8YbNUVfHD:-M7FpWTj3VlC4WICp40D:b-xx77eg) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/30b321dcada4105889be968ea7609f99fe4df785/src/components/files-header/FilesHeader.js#L71)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This should be different based on the branches of the source/target repository.
The left should be this one and the right one should be: `https://bg.door43.org/unfoldingWord/en_tn/src/branch/klappy-tc-create-1/LICENSE.md`
</blockquote></details>

So in the sourceChip, I'm using sourceRepository information (html_url). Analogously, for targetChip.  Are the entire chips misplaced?

**Comment by klappy** [comment]
___
*[src/components/files-header/FilesHeader.js, line 71 at r3](https://reviewable.io/reviews/unfoldingword/tc-create-app/135#-M78ny4B7AU8YbNUVfHD:-M7GH3a16n7vK8cx8wJ2:b5pqkrf) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/30b321dcada4105889be968ea7609f99fe4df785/src/components/files-header/FilesHeader.js#L71)):*
<details><summary><i>Previously, mandolyte wrote…</i></summary><blockquote>

So in the sourceChip, I'm using sourceRepository information (html_url). Analogously, for targetChip.  Are the entire chips misplaced?
</blockquote></details>

They appear to be in the right spots. Source on the left and target on the right.

**Comment by klappy** [comment]
___
*[src/components/files-header/FilesHeader.js, line 84 at r3](https://reviewable.io/reviews/unfoldingword/tc-create-app/135#-M7GHkxv5iRhUmznED7R:-M7GHkxw3x_MNjTSDXxA:bctj70r) ([raw file](https://github.com/unfoldingword/tc-create-app/blob/30b321dcada4105889be968ea7609f99fe4df785/src/components/files-header/FilesHeader.js#L84)):*
> ```JavaScript
>     const iconTooltip='OpenTargetText';
>     const deleteIconTooltip = 'CompareTarget'
>     const licenseLink= targetRepository.html_url+'/src/branch/master/LICENSE.md';
> ```

This should replace master with the custom branch that the user is edit and is in the target repository.

**Pull request merged**
