### PR TITLE
added circular progress spinner for language dropdown

### PR DESCRIPTION
**Pull request by jincypjose**
added circular progress spinner for language drop down if data for the drop down is available else it shows 'No language found'

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/1230)

### CODE REVIEW

**Comment by klappy** [comment]
Looks good!

Can you center the spinner horizontally?
Make sure that the rendered drop down and text isn’t affected by the centering. 
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Mobile Safari 15.3 on iOS 15.3.1
Viewport:  390 x 396 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1230--tc-create-app.netlify.app%2F&os=iOS&os_version=15.3&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1230--tc-create-app.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=624b1a489bb5680009b8d13a&commentID=624bed4284a6e464e5da776c&resolution=resolved)

**Review by klappy — CHANGES_REQUESTED** [review]
Looking good!

I left a comment for centering just the spinner. It will look more natural that way. 

image

**Review by Joel-C-Johnson — APPROVED** [review]
Looks Good

**Review by klappy — APPROVED** [review]
LGTM!

**Pull request merged**
