### PR TITLE
Performance enhancements, reducing rerendering

### PR DESCRIPTION
**Pull request by klappy**
Adding `use-deep-compare` library to compare arrays/objects in react lifecycle hooks.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/1135)

### CODE REVIEW

**Comment by klappy** [comment]
before:
Screen Shot 2022-01-06 at 6 21 27 PM

after:
Screen Shot 2022-01-06 at 6 23 05 PM

**Comment by ancientTexts-net** [comment]
@klappy thank you!
I would like to check it out

**Review by jincypjose — APPROVED** [review]
> Reviewed 3 of 10 files at r1, 7 of 7 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/1135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ancientTexts-net)

**Review by jincypjose — APPROVED** [review]
> Reviewed 2 of 5 files at r7, 4 of 5 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/tc-create-app/1135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ancientTexts-net)

**Pull request closed without merging**
